/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_715028_7[] = { 0, 37, 74 };

// (before - mean) / scale
const float ei_classifier_anom_scale_715028_7[3] = { 0.16435972171957847, 0.16785838949323673, 0.16879602563836543 };
const float ei_classifier_anom_mean_715028_7[3] = { 0.18273744692637528, 0.20080362379736316, 0.18428331260653258 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_715028_7[32] = {
	{ ( float[3] ) { -0.6402732729911804, -1.028099536895752, -0.9900236129760742 }, 0.250908443557536 },
	{ ( float[3] ) { -0.5549059510231018, -0.38215041160583496, -0.5437760353088379 }, 0.3676884879272963 },
	{ ( float[3] ) { -0.5900638699531555, -0.6364849805831909, -0.3002975583076477 }, 0.4036182089436217 },
	{ ( float[3] ) { -1.0487703084945679, -1.0795093774795532, -0.6036245822906494 }, 0.2889626023495631 },
	{ ( float[3] ) { -0.22277307510375977, 2.0051968097686768, 0.9952600002288818 }, 0.627255637199166 },
	{ ( float[3] ) { 1.2390929460525513, -0.6243972182273865, 2.7650320529937744 }, 0 },
	{ ( float[3] ) { -0.28802400827407837, 2.8072099685668945, 0.09817340224981308 }, 0.32502129687826165 },
	{ ( float[3] ) { -0.20672401785850525, 2.386998176574707, -0.5056851506233215 }, 0.6353019787134703 },
	{ ( float[3] ) { 0.9966925978660583, 0.536419153213501, 1.4280455112457275 }, 0.44292960897977113 },
	{ ( float[3] ) { -0.36576929688453674, -0.8403382301330566, -0.6136841773986816 }, 0.3363520861078257 },
	{ ( float[3] ) { 0.8352019786834717, 0.7012913823127747, -0.13974592089653015 }, 0.2805929960150271 },
	{ ( float[3] ) { -1.0067585706710815, -0.7203575372695923, -0.9613023996353149 }, 0.2453110174502588 },
	{ ( float[3] ) { 1.0985794067382812, 0.9113362431526184, -0.5260062217712402 }, 0.3095340172778072 },
	{ ( float[3] ) { 0.5960201025009155, 0.255880743265152, 0.37091127038002014 }, 0.2807397144137412 },
	{ ( float[3] ) { 1.196212887763977, 2.27490496635437, -0.04403230920433998 }, 0.31664231534372644 },
	{ ( float[3] ) { 1.0540658235549927, 1.6721601486206055, 3.1747796535491943 }, 0.21533362926350744 },
	{ ( float[3] ) { 3.3535666465759277, 0.748545229434967, 2.171363592147827 }, 0.22924584253390615 },
	{ ( float[3] ) { -0.25429800152778625, -0.2520166039466858, -0.16515640914440155 }, 0.5613825222659867 },
	{ ( float[3] ) { 0.924694299697876, -0.11752507090568542, 0.8200535774230957 }, 0.3517922291449609 },
	{ ( float[3] ) { 0.6495080590248108, 0.643617570400238, 0.5732868313789368 }, 0.5731327767754794 },
	{ ( float[3] ) { 2.068040370941162, 3.1380157470703125, 1.1170295476913452 }, 0 },
	{ ( float[3] ) { 1.7180107831954956, 1.3972928524017334, 1.5505495071411133 }, 0.23767810870885014 },
	{ ( float[3] ) { 2.0398061275482178, -0.0410456545650959, 1.0320613384246826 }, 0.23075411507704052 },
	{ ( float[3] ) { 0.06123711168766022, 0.6166957020759583, 0.658430278301239 }, 0.2617060393189954 },
	{ ( float[3] ) { 2.072913408279419, 0.886172890663147, -0.10498971492052078 }, 0.6007668863736628 },
	{ ( float[3] ) { 2.039808988571167, 0.6337346434593201, 1.0003814697265625 }, 0.33673875336604464 },
	{ ( float[3] ) { -0.15919619798660278, 0.17492157220840454, 2.780067205429077 }, 0.23233131612196142 },
	{ ( float[3] ) { 0.5074737071990967, -0.19812272489070892, 2.814361572265625 }, 0.29793871466436445 },
	{ ( float[3] ) { -0.6680126190185547, 1.0953983068466187, 1.9819650650024414 }, 0.032928634579086076 },
	{ ( float[3] ) { 3.4958670139312744, 0.060617391020059586, 0.0830901637673378 }, 0 },
	{ ( float[3] ) { 0.023277662694454193, 3.3992631435394287, 0.8973867893218994 }, 0.27908941841626383 },
	{ ( float[3] ) { 1.2382969856262207, 0.3093620240688324, 3.222262382507324 }, 0 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
