/*
 * Copyright (c) 2025 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */

#ifndef _EI_CLASSIFIER_ANOMALY_METADATA_H_
#define _EI_CLASSIFIER_ANOMALY_METADATA_H_

#include "edge-impulse-sdk/classifier/ei_model_types.h"

const uint16_t ei_classifier_anom_axes_800762_11[] = { 0, 67, 134 };

// (before - mean) / scale
const float ei_classifier_anom_scale_800762_11[3] = { 0.07348697416679387, 0.07901177426883225, 0.06876377015868543 };
const float ei_classifier_anom_mean_800762_11[3] = { 0.108930949595524, 0.10650774758891203, 0.10519124155165628 };
const ei_classifier_anom_cluster_t ei_classifier_anom_clusters_800762_11[32] = {
	{ ( float[3] ) { 0.32376429438591003, 1.0866891145706177, 0.1855335831642151 }, 0.6217842143329851 },
	{ ( float[3] ) { -0.4561806917190552, -0.4199000597000122, -0.7414923906326294 }, 0.5516038179022478 },
	{ ( float[3] ) { 1.1782053709030151, 0.7557605504989624, 0.8730777502059937 }, 0.6979455093180108 },
	{ ( float[3] ) { 0.6283413767814636, 0.07788611203432083, 0.847307026386261 }, 0.45965389050290817 },
	{ ( float[3] ) { 0.36129671335220337, 0.757153332233429, 1.3800777196884155 }, 0.4232189497646168 },
	{ ( float[3] ) { -0.36845776438713074, -0.13806523382663727, -0.157533198595047 }, 0.7261561943069993 },
	{ ( float[3] ) { -1.1323846578598022, -1.0739853382110596, -0.7893691658973694 }, 0.3307350455178387 },
	{ ( float[3] ) { 0.30618491768836975, -0.0002563968300819397, 0.27476024627685547 }, 0.4537154797368227 },
	{ ( float[3] ) { -1.2458521127700806, -0.6438168287277222, -1.3853929042816162 }, 0.40220816216081473 },
	{ ( float[3] ) { 0.24240878224372864, 0.08316238969564438, -0.5654049515724182 }, 0.4575074986202568 },
	{ ( float[3] ) { -0.48957574367523193, -0.7323310971260071, -0.2696940302848816 }, 0.532436551420495 },
	{ ( float[3] ) { -0.7923310995101929, -1.1129440069198608, -1.0441964864730835 }, 0.3707668409623102 },
	{ ( float[3] ) { 1.0816171169281006, 0.438435435295105, 0.06988043338060379 }, 0.48845991812715334 },
	{ ( float[3] ) { 0.08779671788215637, -0.3789275288581848, -0.2638707756996155 }, 0.347978816321789 },
	{ ( float[3] ) { 0.9030864238739014, -0.5479391813278198, 0.5031803846359253 }, 0.3812510937502343 },
	{ ( float[3] ) { 2.7114384174346924, 2.5819597244262695, -0.1595993936061859 }, 0.6410076449619228 },
	{ ( float[3] ) { -0.7174180150032043, 0.6628435850143433, 0.6174015998840332 }, 0.7670771659916577 },
	{ ( float[3] ) { 0.9405910968780518, 2.236255645751953, 2.939343214035034 }, 0.40631556551917647 },
	{ ( float[3] ) { 0.26277774572372437, 0.8237900733947754, -0.3987240791320801 }, 0.6594006131599488 },
	{ ( float[3] ) { 2.016371965408325, 1.5320849418640137, 1.7587040662765503 }, 0.4995434709300691 },
	{ ( float[3] ) { -0.8343348503112793, -0.7168014645576477, -0.6644459366798401 }, 0.42698014012959085 },
	{ ( float[3] ) { 1.9322714805603027, 2.180075168609619, 1.2318246364593506 }, 0.5258559148004978 },
	{ ( float[3] ) { 0.06080419942736626, 0.4162088632583618, 0.4886167347431183 }, 0.4356087031991094 },
	{ ( float[3] ) { -0.09074965864419937, -0.7690339684486389, 0.1361205279827118 }, 0.5944572901945424 },
	{ ( float[3] ) { 1.649573802947998, 1.9512444734573364, -0.09478408843278885 }, 0.721310008303348 },
	{ ( float[3] ) { 2.3903961181640625, 2.406811237335205, 1.6899858713150024 }, 0.42654010808882514 },
	{ ( float[3] ) { 0.2741246223449707, -0.7044592499732971, 1.0143370628356934 }, 0.4177469068532114 },
	{ ( float[3] ) { 2.3127071857452393, 1.5476821660995483, 2.7875444889068604 }, 0.8045723080169317 },
	{ ( float[3] ) { -0.05161648988723755, 0.0618332102894783, 0.9687739014625549 }, 0.20437924529560217 },
	{ ( float[3] ) { 1.7421380281448364, -0.24705295264720917, 2.0655555725097656 }, 0.20961956157948797 },
	{ ( float[3] ) { 0.42458727955818176, 1.9525195360183716, 1.7370599508285522 }, 0.43531182100258153 },
	{ ( float[3] ) { 1.2396661043167114, 2.4949545860290527, 2.1164422035217285 }, 0.37700159822249485 },
};

#endif // _EI_CLASSIFIER_ANOMALY_METADATA_H_
